version : '3.8'

services:
  db:
    image: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hello
    networks:
      - mynet
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: hello
    networks:
      - mynet
    depends_on: 
      - db
networks:
  mynet:

  